# Generated by Django 4.2.3 on 2024-11-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='target_direction',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('idle', 'Idle')], default='idle', max_length=4),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='target_floors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
